// Users Actions

export const GET_USER_DETAIL = "GET_USER_DETAIL"
export const GET_USERS_BY_NAME = "GET_USERS_BY_NAME"
export const GET_LOGGED_USER = "GET_LOGGED_USER"
export const GET_LEADERBOARD_RANK = "GET_LEADERBOARD_RANK"
export const POST_GAME_POINTS = "POST_GAME_POINTS"
export const POST_AUTHENTICATE_WITH_GOOGLE = "POST_AUTHENTICATE_WITH_GOOGLE"

// End Users Actions

// Questions Actions

export const GET_RANDOM_QUESTION = "GET_RANDOM_QUESTION"

// End Questions Actions

// Tournaments Actions

export const GET_ALL_TOURNAMENTS = "GET_ALL_TOURNAMENTS"
export const POST_NEW_TOURNAMENT = "POST_NEW_TOURNAMENT"
export const POST_JOIN_TOURNAMENT = "POST_JOIN_TOURNAMENT"
export const POST_TOURNAMENT_POINTS = "POST_TOURNAMENT_POINTS" 

// End Tournaments Actions


export const CLEAR_STATE = "CLEAR_STATE"
export const CLEAR_STATE_USER_DETAIL = "CLEAR_STATE_USER_DETAIL"